# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AP CSP
email: bsk@ms223.org
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/AP-CSP" # the subpath of your site, e.g. /blog
url: "http://bsk.education/AP-CSP" # the base hostname & protocol for your site
twitter_username: bensk
github_username:  bensk
paginate:            1

# Build settings
markdown: kramdown
repo:              https://github.com/bensk/AP-CSP
future: true
gems:
    # - jemoji
    - jekyll-archives
    - jekyll-paginate
